version: '3.8'

services:
  postgres:
    image: postgres:16.1
    ports:
      - '5433:5432'
    env_file:
      /environments/local.env
    volumes:
      - ./api-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3
    ports:
      - '6379:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispass}'
    restart: unless-stopped

  tanya-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "8000:9000"
      - "8001:9001"
    volumes:
      - ./api-s3-data:/usr/src/app/s3
    env_file:
      - /environments/local.env

volumes:
  api-db-data:
  api-s3-data:
